plugins {
    id "com.gradleup.shadow" version "9.4.3"
    id "com.gradle.plugin-publish" version "1.2.1"
    id 'java-gradle-plugin'
    id 'groovy'
    id 'maven-publish'
    id "org.jreleaser" version "1.20.0"
    id 'signing'
    id 'eclipse'
}

ext {
    roboVMVersion = '2.3.26'
    nexusUsername = System.getenv('MAVEN_USERNAME')
    nexusPassword = System.getenv('MAVEN_PASSWORD')
}

group = 'com.mobidevelop.robovm'
base {
    archivesName = 'robovm-gradle-plugin'
}
version "${roboVMVersion}"


java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
    withSourcesJar()
    withJavadocJar()
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
    maven { url 'https://central.sonatype.com/repository/maven-snapshots' }
}

dependencies {
    compileOnly gradleApi()
    compileOnly localGroovy()
    implementation "org.apache.commons:commons-compress:1.22"
    implementation "com.mobidevelop.robovm:robovm-compiler:${roboVMVersion}"
    implementation 'org.sonatype.aether:aether:1.13.1'
    implementation 'org.sonatype.aether:aether-connector-wagon:1.13.1'
    implementation 'org.apache.maven:maven-aether-provider:3.0.4'
    implementation 'org.apache.maven.wagon:wagon-provider-api:2.4'
    implementation 'org.apache.maven.wagon:wagon-http:2.4'
    testImplementation group: 'junit', name: 'junit', version: '4.11'
}

gradlePlugin {
    website = "https://mobivm.github.io"
    vcsUrl = "https://github.com/MobiVM/robovm"
    plugins {
        create("robovm") {
            id = "com.mobidevelop.robovm"
            implementationClass = "org.robovm.gradle.RoboVMPlugin"
            displayName = "RoboVM Gradle Plugin"
            description = "The RoboVM Gradle Plugin provides a way to build RoboVM apps using Gradle."
        }
    }
}

publishing {
    // TODO: while not pushing to Gradle Plugin Portal but to Maven Central we need
    //       to have complete POM with all fields to pass Cental validation
    //       there is no way to configure URLs etc in gradlePlugin {} blocks,
    //       so override both plugin marker's and plugin's POM in configureEach
    //       instead of single `pluginMaven(MavenPublication)`
    publications.withType(MavenPublication).configureEach {
        pom {
            name = 'RoboVM Gradle Plugin'
            description = 'The RoboVM Gradle Plugin provides a way to build RoboVM apps using Gradle.'
            url = 'https://github.com/mobidevelop/robovm/'
            inceptionYear = '2013'

            scm {
                url = 'https://github.com/mobidevelop/robovm.git'
                connection = 'scm:git:git://github.com/mobidevelop/robovm.git'
                developerConnection = 'scm:git:git@github.com:mobidevelop/robovm.git'
            }

            licenses {
                license {
                    name = 'The Apache Software License, Version 2.0'
                    url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                    distribution = 'repo'
                }
            }

            developers {
                developer {
                    id = 'jtakakura'
                    name = 'Junji Takakura'
                }
                developer {
                    id = 'ntherning'
                    name = 'Niklas Therning'
                }
            }
        }
    }
    repositories {
        if (project.version.toString().endsWith("-SNAPSHOT")) {
            // snapshots are going to sonatype
            maven {
                credentials {
                    username = System.getenv("MAVEN_USERNAME")
                    password = System.getenv("MAVEN_PASSWORD")
                }
                url = uri("https://central.sonatype.com/repository/maven-snapshots/")
            }
        } else {
            // local staging repository for JReleaser
            maven {
                url = uri(layout.buildDirectory.dir("staging-deploy"))
            }
        }
    }
}


// https://central.sonatype.org/publish/publish-portal-gradle/
jreleaser {
    signing {
        setActive("ALWAYS")
        armored = true
    }
    deploy {
        maven {
            mavenCentral {
                create("sonatype") {
                    setActive("RELEASE")
                    username = System.getenv("MAVEN_USERNAME")
                    password = System.getenv("MAVEN_PASSWORD")
                    url = "https://central.sonatype.com/api/v1/publisher"
                    stagingRepository("build/staging-deploy")
                    setStage("UPLOAD") // OTHERWISE it will do "publish"
                }
            }
        }
    }
    release {
        github {
            skipRelease = true
            token = "-" // must be not blank
        }
    }
}


shadowJar {
    archiveClassifier.set((String) null)
    relocate 'org.apache.http', 'com.mobidevelop.robovm.org.apache.http'
    relocate 'org.apache.commons.io', 'com.mobidevelop.robovm.org.apache.commons.io'
    relocate 'org.objectweb.asm', 'com.mobidevelop.robovm.asm'
}

// suppress "warning: no comment"
tasks.withType(Javadoc) {
    options.addBooleanOption("Xdoclint:-missing", true)
}

signing {
    required { !version.endsWith('SNAPSHOT') && gradle.taskGraph.hasTask("publish") }
    sign publishing.publications.matching { it instanceof MavenPublication }
}

assemble.dependsOn('shadowJar')
publishToMavenLocal.dependsOn('shadowJar')
publish.dependsOn('shadowJar')

tasks.withType(AbstractPublishToMaven).configureEach {
    dependsOn(tasks.withType(Sign))
}
