/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_ch_SocketChannelImpl_DefaultOptionsHolder */

#ifndef _Included_sun_nio_ch_SocketChannelImpl_DefaultOptionsHolder
#define _Included_sun_nio_ch_SocketChannelImpl_DefaultOptionsHolder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
