/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_ch_EPollPort */

#ifndef _Included_sun_nio_ch_EPollPort
#define _Included_sun_nio_ch_EPollPort
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_nio_ch_EPollPort_POLLIN
#define sun_nio_ch_EPollPort_POLLIN 1L
#undef sun_nio_ch_EPollPort_POLLOUT
#define sun_nio_ch_EPollPort_POLLOUT 4L
#undef sun_nio_ch_EPollPort_POLLERR
#define sun_nio_ch_EPollPort_POLLERR 8L
#undef sun_nio_ch_EPollPort_POLLHUP
#define sun_nio_ch_EPollPort_POLLHUP 16L
#undef sun_nio_ch_EPollPort_MAX_EPOLL_EVENTS
#define sun_nio_ch_EPollPort_MAX_EPOLL_EVENTS 512L
#undef sun_nio_ch_EPollPort_ENOENT
#define sun_nio_ch_EPollPort_ENOENT 2L
/*
 * Class:     sun_nio_ch_EPollPort
 * Method:    socketpair
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_sun_nio_ch_EPollPort_socketpair
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     sun_nio_ch_EPollPort
 * Method:    interrupt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sun_nio_ch_EPollPort_interrupt
  (JNIEnv *, jclass, jint);

/*
 * Class:     sun_nio_ch_EPollPort
 * Method:    drain1
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sun_nio_ch_EPollPort_drain1
  (JNIEnv *, jclass, jint);

/*
 * Class:     sun_nio_ch_EPollPort
 * Method:    close0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sun_nio_ch_EPollPort_close0
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
