/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_ch_EPoll */

#ifndef _Included_sun_nio_ch_EPoll
#define _Included_sun_nio_ch_EPoll
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_nio_ch_EPoll_EPOLL_CTL_ADD
#define sun_nio_ch_EPoll_EPOLL_CTL_ADD 1L
#undef sun_nio_ch_EPoll_EPOLL_CTL_DEL
#define sun_nio_ch_EPoll_EPOLL_CTL_DEL 2L
#undef sun_nio_ch_EPoll_EPOLL_CTL_MOD
#define sun_nio_ch_EPoll_EPOLL_CTL_MOD 3L
#undef sun_nio_ch_EPoll_EPOLLONESHOT
#define sun_nio_ch_EPoll_EPOLLONESHOT 1073741824L
/*
 * Class:     sun_nio_ch_EPoll
 * Method:    eventSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_EPoll_eventSize
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_EPoll
 * Method:    eventsOffset
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_EPoll_eventsOffset
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_EPoll
 * Method:    dataOffset
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_EPoll_dataOffset
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_EPoll
 * Method:    epollCreate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_EPoll_epollCreate
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_ch_EPoll
 * Method:    epollCtl
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_EPoll_epollCtl
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     sun_nio_ch_EPoll
 * Method:    epollWait
 * Signature: (IJI)I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_EPoll_epollWait
  (JNIEnv *, jclass, jint, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
