/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_fs_LinuxWatchService_LinuxWatchKey */

#ifndef _Included_sun_nio_fs_LinuxWatchService_LinuxWatchKey
#define _Included_sun_nio_fs_LinuxWatchService_LinuxWatchKey
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_nio_fs_LinuxWatchService_LinuxWatchKey_MAX_EVENT_LIST_SIZE
#define sun_nio_fs_LinuxWatchService_LinuxWatchKey_MAX_EVENT_LIST_SIZE 512L
#ifdef __cplusplus
}
#endif
#endif
