/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_fs_UnixCopyFile_Flags */

#ifndef _Included_sun_nio_fs_UnixCopyFile_Flags
#define _Included_sun_nio_fs_UnixCopyFile_Flags
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
