/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_fs_LinuxWatchService */

#ifndef _Included_sun_nio_fs_LinuxWatchService
#define _Included_sun_nio_fs_LinuxWatchService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sun_nio_fs_LinuxWatchService
 * Method:    eventSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_fs_LinuxWatchService_eventSize
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_fs_LinuxWatchService
 * Method:    eventOffsets
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_sun_nio_fs_LinuxWatchService_eventOffsets
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_fs_LinuxWatchService
 * Method:    inotifyInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sun_nio_fs_LinuxWatchService_inotifyInit
  (JNIEnv *, jclass);

/*
 * Class:     sun_nio_fs_LinuxWatchService
 * Method:    inotifyAddWatch
 * Signature: (IJI)I
 */
JNIEXPORT jint JNICALL Java_sun_nio_fs_LinuxWatchService_inotifyAddWatch
  (JNIEnv *, jclass, jint, jlong, jint);

/*
 * Class:     sun_nio_fs_LinuxWatchService
 * Method:    inotifyRmWatch
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_sun_nio_fs_LinuxWatchService_inotifyRmWatch
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     sun_nio_fs_LinuxWatchService
 * Method:    configureBlocking
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_sun_nio_fs_LinuxWatchService_configureBlocking
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     sun_nio_fs_LinuxWatchService
 * Method:    socketpair
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_sun_nio_fs_LinuxWatchService_socketpair
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     sun_nio_fs_LinuxWatchService
 * Method:    poll
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_sun_nio_fs_LinuxWatchService_poll
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
