package org.robovm.ibxcode.consts;

/**
 * constant strings to form final file
 */
public class StringConsts {
    public final static String EXPORT_FILE_HEADER =
            " * This file has been auto-generated by\n" +
            " * RoboVM's Interface Builder Integrator.\n" +
            " * It is used to provide Java class visibility to IntefaceBuilder\n" +
            " * DO NOT MODIFY! DO NOT ADD UNDER VERSION CONTROL";
}
