/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.robovm.libimobiledevice.binding;

public class DebugServerCommandRefOut {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DebugServerCommandRefOut(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DebugServerCommandRefOut obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LibIMobileDeviceJNI.delete_DebugServerCommandRefOut(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DebugServerCommandRef getValue() {
    long cPtr = LibIMobileDeviceJNI.DebugServerCommandRefOut_value_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DebugServerCommandRef(cPtr, false);
  }

  public DebugServerCommandRefOut() {
    this(LibIMobileDeviceJNI.new_DebugServerCommandRefOut(), true);
  }

}
