/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.robovm.libimobiledevice.binding;

public class IDeviceInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IDeviceInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IDeviceInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(IDeviceInfo obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LibIMobileDeviceJNI.delete_IDeviceInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUdid(String value) {
    LibIMobileDeviceJNI.IDeviceInfo_udid_set(swigCPtr, this, value);
  }

  public String getUdid() {
    return LibIMobileDeviceJNI.IDeviceInfo_udid_get(swigCPtr, this);
  }

  public void setConnectionType(IDeviceConnectiontype value) {
    LibIMobileDeviceJNI.IDeviceInfo_connectionType_set(swigCPtr, this, value.swigValue());
  }

  public IDeviceConnectiontype getConnectionType() {
    return IDeviceConnectiontype.swigToEnum(LibIMobileDeviceJNI.IDeviceInfo_connectionType_get(swigCPtr, this));
  }

  public void setConn_data(IDeviceInfoConnData value) {
    LibIMobileDeviceJNI.IDeviceInfo_conn_data_set(swigCPtr, this, IDeviceInfoConnData.getCPtr(value), value);
  }

  public IDeviceInfoConnData getConn_data() {
    long cPtr = LibIMobileDeviceJNI.IDeviceInfo_conn_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new IDeviceInfoConnData(cPtr, false);
  }

  public IDeviceInfo() {
    this(LibIMobileDeviceJNI.new_IDeviceInfo(), true);
  }

}
