/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.robovm.libimobiledevice.binding;

public enum IDeviceOptions {
  IDEVICE_LOOKUP_USBMUX(1 << 1),
  IDEVICE_LOOKUP_NETWORK(1 << 2),
  IDEVICE_LOOKUP_PREFER_NETWORK(1 << 3);

  public final int swigValue() {
    return swigValue;
  }

  public static IDeviceOptions swigToEnum(int swigValue) {
    IDeviceOptions[] swigValues = IDeviceOptions.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (IDeviceOptions swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + IDeviceOptions.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private IDeviceOptions() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private IDeviceOptions(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private IDeviceOptions(IDeviceOptions swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

