/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.robovm.libimobiledevice.binding;

public enum LockdowndError {
  LOCKDOWN_E_SUCCESS(0),
  LOCKDOWN_E_INVALID_ARG(-1),
  LOCKDOWN_E_INVALID_CONF(-2),
  LOCKDOWN_E_PLIST_ERROR(-3),
  LOCKDOWN_E_PAIRING_FAILED(-4),
  LOCKDOWN_E_SSL_ERROR(-5),
  LOCKDOWN_E_DICT_ERROR(-6),
  LOCKDOWN_E_RECEIVE_TIMEOUT(-7),
  LOCKDOWN_E_MUX_ERROR(-8),
  LOCKDOWN_E_NO_RUNNING_SESSION(-9),
  LOCKDOWN_E_INVALID_RESPONSE(-10),
  LOCKDOWN_E_MISSING_KEY(-11),
  LOCKDOWN_E_MISSING_VALUE(-12),
  LOCKDOWN_E_GET_PROHIBITED(-13),
  LOCKDOWN_E_SET_PROHIBITED(-14),
  LOCKDOWN_E_REMOVE_PROHIBITED(-15),
  LOCKDOWN_E_IMMUTABLE_VALUE(-16),
  LOCKDOWN_E_PASSWORD_PROTECTED(-17),
  LOCKDOWN_E_USER_DENIED_PAIRING(-18),
  LOCKDOWN_E_PAIRING_DIALOG_RESPONSE_PENDING(-19),
  LOCKDOWN_E_MISSING_HOST_ID(-20),
  LOCKDOWN_E_INVALID_HOST_ID(-21),
  LOCKDOWN_E_SESSION_ACTIVE(-22),
  LOCKDOWN_E_SESSION_INACTIVE(-23),
  LOCKDOWN_E_MISSING_SESSION_ID(-24),
  LOCKDOWN_E_INVALID_SESSION_ID(-25),
  LOCKDOWN_E_MISSING_SERVICE(-26),
  LOCKDOWN_E_INVALID_SERVICE(-27),
  LOCKDOWN_E_SERVICE_LIMIT(-28),
  LOCKDOWN_E_MISSING_PAIR_RECORD(-29),
  LOCKDOWN_E_SAVE_PAIR_RECORD_FAILED(-30),
  LOCKDOWN_E_INVALID_PAIR_RECORD(-31),
  LOCKDOWN_E_INVALID_ACTIVATION_RECORD(-32),
  LOCKDOWN_E_MISSING_ACTIVATION_RECORD(-33),
  LOCKDOWN_E_SERVICE_PROHIBITED(-34),
  LOCKDOWN_E_ESCROW_LOCKED(-35),
  LOCKDOWN_E_PAIRING_PROHIBITED_OVER_THIS_CONNECTION(-36),
  LOCKDOWN_E_FMIP_PROTECTED(-37),
  LOCKDOWN_E_MC_PROTECTED(-38),
  LOCKDOWN_E_MC_CHALLENGE_REQUIRED(-39),
  LOCKDOWN_E_UNKNOWN_ERROR(-256);

  public final int swigValue() {
    return swigValue;
  }

  public static LockdowndError swigToEnum(int swigValue) {
    LockdowndError[] swigValues = LockdowndError.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (LockdowndError swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + LockdowndError.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private LockdowndError() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private LockdowndError(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private LockdowndError(LockdowndError swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

