/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.robovm.libimobiledevice.binding;

public class LockdowndServiceDescriptorStruct {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected LockdowndServiceDescriptorStruct(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LockdowndServiceDescriptorStruct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(LockdowndServiceDescriptorStruct obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LibIMobileDeviceJNI.delete_LockdowndServiceDescriptorStruct(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPort(short value) {
    LibIMobileDeviceJNI.LockdowndServiceDescriptorStruct_port_set(swigCPtr, this, value);
  }

  public short getPort() {
    return LibIMobileDeviceJNI.LockdowndServiceDescriptorStruct_port_get(swigCPtr, this);
  }

  public void setSslEnabled(boolean value) {
    LibIMobileDeviceJNI.LockdowndServiceDescriptorStruct_sslEnabled_set(swigCPtr, this, value);
  }

  public boolean getSslEnabled() {
    return LibIMobileDeviceJNI.LockdowndServiceDescriptorStruct_sslEnabled_get(swigCPtr, this);
  }

  public void setIdentifier(String value) {
    LibIMobileDeviceJNI.LockdowndServiceDescriptorStruct_identifier_set(swigCPtr, this, value);
  }

  public String getIdentifier() {
    return LibIMobileDeviceJNI.LockdowndServiceDescriptorStruct_identifier_get(swigCPtr, this);
  }

  public LockdowndServiceDescriptorStruct() {
    this(LibIMobileDeviceJNI.new_LockdowndServiceDescriptorStruct(), true);
  }

}
