/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.robovm.libimobiledevice.binding;

public enum LockdowndCuPairingCbType {
  LOCKDOWN_CU_PAIRING_PIN_REQUESTED,
  LOCKDOWN_CU_PAIRING_DEVICE_INFO,
  LOCKDOWN_CU_PAIRING_ERROR;

  public final int swigValue() {
    return swigValue;
  }

  public static LockdowndCuPairingCbType swigToEnum(int swigValue) {
    LockdowndCuPairingCbType[] swigValues = LockdowndCuPairingCbType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (LockdowndCuPairingCbType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + LockdowndCuPairingCbType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private LockdowndCuPairingCbType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private LockdowndCuPairingCbType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private LockdowndCuPairingCbType(LockdowndCuPairingCbType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

