buildscript {
    ext.roboVMVersion = "__robovmVersion__"
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
        maven { url 'https://central.sonatype.com/repository/maven-snapshots' }
    }
    dependencies {
        classpath "com.mobidevelop.robovm:robovm-gradle-plugin:${roboVMVersion}"
    }
}

apply plugin: 'java'
apply plugin: 'robovm'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
    maven { url 'https://central.sonatype.com/repository/maven-snapshots' }
}

robovm {
}

dependencies {
    implementation "com.mobidevelop.robovm:robovm-rt:${roboVMVersion}"
    implementation "com.mobidevelop.robovm:robovm-cocoatouch:${roboVMVersion}"
    testImplementation "junit:junit:4.12"
}
