# this workflow builds native libhfscompressor for MacOSX
# once build it will create a branch and commit all changes to it
# it allow then to merge received artifacts to master
name: "Build libhfscompressor (MacOSX)"
on:
  workflow_dispatch:
    inputs:
      scriptArgs:
        description: 'Arguments to build.sh'
      targetBranch:
        description: 'Target branch to push artifacts'
        required: true
      commitMessage:
        description: 'Commit message'
jobs:
  printInputs:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Install dependencies
        run: |
          brew install autoconf automake pkg-config libtool cmake
      - name: Build libhfscompressor natives
        run: |
          cd compiler/libhfscompressor
          ./build.sh ${{ github.event.inputs.scriptArgs }}
      - name: Push changes to the branch
        run: |
          git checkout -b "${{ github.event.inputs.targetBranch }}"
          git add compiler/bin
          git commit -m "${{ github.event.inputs.commitMessage }}"
          git push --set-upstream origin "${{ github.event.inputs.targetBranch }}"